In [299]:
from scipy.misc import imread, imsave, imresize

# Read an JPEG image into a numpy array
img = imread('C:\Program Files\Anaconda3/cat.jpg')
#print(img,img.dtype, img.shape)  # Prints "uint8 (400, 248, 3)"

img_tinted = img * [1, 0.95, 0.9]
#print(img_tinted)

img_tinted = imresize(img_tinted, (300, 300))
print(img_tinted)
imsave('C:\Program Files\Anaconda3/catttt_tinted.jpg', img_tinted)

[[[133 122 105]
  [148 137 119]
  [169 155 135]
  ..., 
  [ 76  63  38]
  [ 72  58  35]
  [ 63  49  27]]

 [[136 125 108]
  [148 136 117]
  [165 152 131]
  ..., 
  [ 72  59  34]
  [ 68  54  31]
  [ 61  48  26]]

 [[139 127 108]
  [145 132 112]
  [160 146 124]
  ..., 
  [ 66  55  29]
  [ 63  52  27]
  [ 60  50  24]]

 ..., 
 [[119 142  70]
  [110 133  63]
  [105 129  60]
  ..., 
  [114  97  70]
  [110  94  68]
  [111  95  67]]

 [[111 133  63]
  [110 132  63]
  [108 130  63]
  ..., 
  [111  92  68]
  [106  88  64]
  [102  86  60]]

 [[119 138  71]
  [116 136  68]
  [112 133  66]
  ..., 
  [ 96  77  55]
  [ 94  75  53]
  [ 90  72  49]]]
